apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper
  namespace: argocd
spec:
  project: default
  source:
    chart: gatekeeper
    repoURL: https://open-policy-agent.github.io/gatekeeper/charts
    targetRevision: 3.16.3
    helm:
      releaseName: gatekeeper
      valueFiles:
        - gatekeeper/dev-custom-values.yaml
    ref: main
    repoURL: 'https://github.com/imlavish1012/argo-cd.git'
    targetRevision: main
    path: gatekeeper
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gatekeeper
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true