apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  sources:
    - chart: nginx
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 18.1.11
      helm:
        valueFiles:
        - $values/nginx/dev-custom-values.yaml
    # Values from Git
    - repoURL: 'https://github.com/imlavish1012/argo-cd'
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true